blank_issues_enabled: false
contact_links:
  - name: Documentation 📚
    url: https://www.chromatic.com/docs/
    about: Read the official docs for answers to common questions.
  - name: Get support 💬
    url: https://www.chromatic.com/docs/support
    about: Contact us in the in-app chat, or reach out via email.
